### ISSUE TITLE
Crafting recipes with apostrophe cannot be searched

### ISSUE THREAD

**Issue by DenL** [goaaats/Dalamud.FindAnything#18]
Since the latest update crafting recpies with apostrophe does not show up in search results with or without spostrophe, see below:

Recipe show up before getting to the apostrophe
![image](https://user-images.githubusercontent.com/5632219/160295436-7594d7f0-e80e-4a8d-95ae-0ff5e444a1a4.png)

With apostrophe
![image](https://user-images.githubusercontent.com/5632219/160295454-bab4a3c9-61d7-4cda-8a6a-b521c1302b0f.png)

Without spostrophe
![image](https://user-images.githubusercontent.com/5632219/160295465-4fc2878b-7655-4651-842a-8e155222ea8b.png)

**Comment by goaaats** [comment]
Fixed this, thanks
