### ISSUE TITLE
Allow Right Enter to confirm selection

### ISSUE THREAD

**Issue by drejjmit** [goaaats/Dalamud.FindAnything#37]
Currently only Left Enter confirms a selection.
Would it be possible to make Right Enter (NumLock Enter) also confirm selection?

![image](https://user-images.githubusercontent.com/15526476/182083727-7028b778-7b21-4ae5-a8c7-a2c9bc7a4cc3.png)

**Comment by goaaats** [comment]
It used to, but I assumed that broke with recent changes. I don't have a numpad to test with but I'll have a look.
