### ISSUE TITLE
When in combat, toast message that appears when trying to use the teleport features states "Will only work with teleporter plugin installed", even with Teleporter plugin installed

### ISSUE THREAD

**Issue by KylerNyhagen** [goaaats/Dalamud.FindAnything#4]
When attempting to teleport using Wotsit, if you are in combat, the following Toast notification displays:

![image](https://user-images.githubusercontent.com/19742998/146645571-9b567b2a-e130-42c1-a243-fe612fc5deef.png)

The one that Teleporter plugin lists is a simple "Cannot execute at this time".

**Comment by goaaats** [comment]
This is already fixed, just need to push an update 👍
