### ISSUE TITLE
Dungeon entries perform no action

### ISSUE THREAD

**Issue by zeroeightysix** [goaaats/Dalamud.FindAnything#43]
Since wotsit updated for 6.2, selecting dungeons from the menu no longer opens duty finder.

**Comment by drejjmit** [comment]
Same for me. Nothing happens when i click the dungeon/trial

![image](https://user-images.githubusercontent.com/15526476/187564354-5d2e05cf-7bc2-412c-bac2-262730987658.png)

**Comment by drejjmit** [comment]
Any update on this?
