### ISSUE TITLE
Prefix search modifiers

### ISSUE THREAD

**Issue by liamdawson** [goaaats/Dalamud.FindAnything#8]
It'd be awesome if I could switch to different "modes" by changing the first character, and optionally have hotkeys to open with that first character set (like Visual Studio Code does with Ctrl-P vs. Ctrl-Shift-P).

I'm only really aware of two modes right now, "normal" and wiki, so those could be differentiated as:

- `BTN` - would show my botanist gear set
- `?BTN` - would offer to 'Search for "BTN" in wikis...'

**Comment by goaaats** [comment]
I implemented this, you can assign an additional modifier key in the settings.
